### PR TITLE
Allow custom nolluprc file

### PR DESCRIPTION
**Pull request by sup-ham**

### CODE REVIEW

**Comment by PepsRyuu** [comment]
There's no error checking on the CLI and there is duplicate code for loading the config file.

What's the use case for this option?

**Comment by sup-ham** [comment]
just to move config somewhere like so `nollup --rc config/nolluprc.js`

**Comment by PepsRyuu** [comment]
Sounds good! Just need to add that error check for missing value and remove the duplicate code. Also documentation would need to be updated for the CLI, and dev server. For consistency, maybe ```options.rc```?

**Comment by sup-ham** [comment]
done.. @PepsRyuu please review

**Comment by PepsRyuu** [comment]
Apologies for the delay. I released a version of this in ```0.16.0```: https://github.com/PepsRyuu/nollup/commit/7315cb25e893456e8e4a21b018b514a11ead673f Hope this helps satisfy your requirement!

**Comment by sup-ham** [comment]
@PepsRyuu, ok thank a lot

**Pull request closed without merging**
