### PR TITLE
Fix outputOptions hook

### PR DESCRIPTION
**Pull request by rixo**
`outputOptions` hook wasn't passed the options when called from the middleware.

I've also set the executable bit on `cli.js` -- otherwise it doesn't work when Nollup is npm linked in a project with Linux.

### CODE REVIEW

**Comment by PepsRyuu** [comment]
Looks good! Any more changes you're in the process of or is it all good to merge? :)

**Comment by rixo** [comment]
It's ok for now.

I'm also trying to see why my source maps (svelte) are off with Nollup, but that's another story... Any idea maybe?

**Comment by PepsRyuu** [comment]
If you can provide something reproducible in a new issue, I can have a look at that as well! :)

**Comment by rixo** [comment]
You can see it in my [svelte template](https://github.com/rixo/svelte-template-hot), but I'd like to ensure this is not caused by my own HMR code transform, and maybe clean the repro a little before opening a proper issue.

`npm run dev` uses my hot plugin and sourcemaps are ok

with `npm run dev:nollup` they're not :-/

**Comment by PepsRyuu** [comment]
Released PR in ```0.11.1```

**Pull request merged**
