### PR TITLE
#74: sourcesContent.length undefined fix.

### PR DESCRIPTION
**Pull request by houd1ni**
Fixes https://github.com/PepsRyuu/nollup/issues/74

### CODE REVIEW

**Comment by pillowsoft** [comment]
This fixes an issue I am seeing similar to #74 (same error output) with a project I have in svelte & typescript. Any chance this can get merged? All the PR is doing is adding a check to ensure `obj.map.sourcesContent` exists before dereferencing `length`. Thanks!

**Comment by PepsRyuu** [comment]
@pillowsoft Can you provide a reproducible example of this? I don't mind merging but for regression purposes I need something that can trigger the issue.

**Comment by pillowsoft** [comment]
@PepsRyuu alas it's a large app that after adding some new code, started experiencing the issue in #74. I'm not sure what I added that caused the issue, but adding the check before the dereferencing makes it work. For now, I have it patched locally so that I can continue development. I figure adding the dereference test is pretty innocuous unless it's masking some bigger issue of course.  Sorry, that I can't come up with a simple repro case. You could modify the PR and output a warning log if `length` is not defined. That would keep others from running into the issue I did while making it known that something is not working internally as you would expect. I assume that you expect that`sourcesContent` should always be defined?

**Comment by PepsRyuu** [comment]
Can you share the Rollup config? Maybe there's something in common between the reported configs so far. 🤔

The expectation is that the array should always exist, at least from what I've seen so far. But yes I am worried that without a proper reproduction that we might be missing something.

**Comment by pillowsoft** [comment]
@PepsRyuu Here it is. Let me know if you would like me to try changing anything in it. Thanks!!!

**rollup.config.js**

```
import svelte from 'rollup-plugin-svelte-hot';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';
import postcssHot from 'rollup-plugin-postcss-hot';
import postcss from 'rollup-plugin-postcss';
import { injectManifest } from 'rollup-plugin-workbox';

import hmr from 'rollup-plugin-hot';
import typescript from 'rollup-plugin-typescript2';
import { config } from 'dotenv';
import injectProcessEnv from 'rollup-plugin-inject-process-env';
const css = require('rollup-plugin-hot-css');
import path from 'path';
import del from 'rollup-plugin-delete';
import json from '@rollup/plugin-json';
import url from '@rollup/plugin-url';
// import { typescriptPaths } from 'rollup-plugin-typescript-paths';

// Set this to true to pass the --single flag to sirv (this serves your
// index.html for any unmatched route, which is a requirement for SPA
// routers using History API / pushState)
//
// NOTE This will have no effect when running with Nollup. For Nollup, you'd
// have to add the --history-api-fallback yourself in your package.json
// scripts (see: https://github.com/PepsRyuu/nollup/#nollup-options)
//
const spa = false;

// NOTE The NOLLUP env variable is picked by various HMR plugins to switch
// in compat mode. You should not change its name (and set the env variable
// yourself if you launch nollup with custom commands).
const nollup = !!process.env.NOLLUP;
const watch = !!process.env.ROLLUP_WATCH;
const useLiveReload = !!process.env.LIVERELOAD;
const dev = watch || useLiveReload;
const production = !dev;
const hot = watch && !useLiveReload;
const svelteOptions = require('./svelte.config');
const extensions = ['.js', '.jsx', '.ts', '.tsx'];

const postCssBaseOptions = {
  use: ['less'],
  sourceMap: true,
  plugins: [
    require('postcss-import'),
    require('postcss-preset-env')({ stage: 1 }),
  ],
};

console.log('-----------------------');
console.log('env parsed:', config().parsed);
console.log('hot:', hot);
console.log('production:', production);
console.log('nollup:', nollup);
console.log('watch:', watch);
console.log('useLiveReload:', useLiveReload);
console.log('-----------------------');

const workboxConfig = [
  injectManifest({
    swSrc: '__generated/service-worker.js',
    swDest: 'public/service-worker.js',
    globDirectory: 'public',
    mode: 'production',
  }),
];

const appConfig = {
  input: 'src/main.ts',
  output: {
    sourcemap: true,
    format: 'iife',
    name: 'app',
    file: 'public/build/bundle.js',
  },
  plugins: [
    json(),

    svelte({
      ...svelteOptions,
      // enable run-time checks when not in production
      dev: !production,
      // We'll extract any component CSS out into a separate file — better for
      // performance
      // NOTE when hot option is enabled, this gets automatically be turned to
      // false because CSS extraction doesn't work with HMR currently
      css: (css) => {
        css.write('public/build/bundle.css');
      },
      hot: hot && {
        // Optimistic will try to recover from runtime
        // errors during component init
        optimistic: true,
        // Turn on to disable preservation of local component
        // state -- i.e. non exported `let` variables
        noPreserveState: false,

        // See docs of rollup-plugin-svelte-hot for all available options:
        //
        // https://github.com/rixo/rollup-plugin-svelte-hot#usage
      },
    }),

    hot
      ? postcssHot({
          ...postCssBaseOptions,
          hot,
          extract: path.resolve(''),
        })
      : postcss({
          ...postCssBaseOptions,
          extract: 'postcss-bundle.css',
        }),

    url({
      // by default, rollup-plugin-url will not handle font files
      include: ['**/*.woff', '**/*.woff2', '**/*.eot', '**/*.ttf'],
      // setting infinite limit will ensure that the files
      // are always bundled with the code, not copied to /dist
      limit: Infinity,
    }),

    // If you have external dependencies installed from
    // npm, you'll most likely need these plugins. In
    // some cases you'll need additional configuration -
    // consult the documentation for details:
    // https://github.com/rollup/plugins/tree/master/packages/commonjs
    resolve({
      extensions,
      browser: true,
      dedupe: (importee) =>
        importee === 'svelte' || importee.startsWith('svelte/'),
    }),
    commonjs(),

    // no service worker in dev
    !production && del({ targets: 'public/service-worker.js' }),

    typescript({ sourceMap: !production }),

    injectProcessEnv({
      NODE_ENV: production ? '"production"' : '"dev"',
      ...config().parsed, // attached the .env config
      // SOME_OBJECT: { one: 1, two: [1,2], three: '3' },
      // UNUSED: null
    }),

    // In dev mode, call `npm run start` once
    // the bundle has been generated
    dev && !nollup && serve(),

    // Watch the `public` directory and refresh the
    // browser on changes when not in production
    useLiveReload && livereload('public'),

    // If we're building for production (npm run build
    // instead of npm run dev), minify
    production && terser(),

    ...(production ? workboxConfig : []),

    hmr({
      public: 'public',
      inMemory: true,

      // Default host for the HMR server is localhost, change this option if
      // you want to serve over the network
      // host: '0.0.0.0',
      // You can also change the default HMR server port, if you fancy
      // port: '12345'

      // This is needed, otherwise Terser (in npm run build) chokes
      // on import.meta. With this option, the plugin will replace
      // import.meta.hot in your code with module.hot, and will do
      // nothing else.
      compatModuleHot: !hot,
    }),
  ],
  watch: {
    clearScreen: false,
  },
};

const swConfig = {
  input: 'src/serviceWorker.ts',
  output: {
    sourcemap: true,
    format: 'iife',
    name: 'sw',
    file: '__generated/service-worker.js',
  },
  plugins: [
    // If you have external dependencies installed from
    // npm, you'll most likely need these plugins. In
    // some cases you'll need additional configuration -
    // consult the documentation for details:
    // https://github.com/rollup/plugins/tree/master/packages/commonjs
    resolve({
      extensions,
      browser: true,
      dedupe: (importee) =>
        importee === 'svelte' || importee.startsWith('svelte/'),
    }),
    commonjs(),

    typescript({
      sourceMap: !production,
      tsconfig: path.join(__dirname, 'tsconfig-service-worker.json'),
    }),

    injectProcessEnv({
      NODE_ENV: production ? '"production"' : '"dev"',
      ...config().parsed, // attached the .env config
      // SOME_OBJECT: { one: 1, two: [1,2], three: '3' },
      // UNUSED: null
    }),

    ...(production ? workboxConfig : []),
  ],
  watch: {
    clearScreen: false,
  },
};

export default [swConfig, appConfig];

function serve() {
  let started = false;
  return {
    name: 'serve',
    writeBundle() {
      if (!started) {
        started = true;
        const flags = ['run', 'start', '--', '--dev'];
        if (spa) {
          flags.push('--single');
        }
        require('child_process').spawn('npm', flags, {
          stdio: ['ignore', 'inherit', 'inherit'],
          shell: true,
        });
      }
    },
  };
}
```

**svelte.config.js**

```
const sveltePreprocess = require('svelte-preprocess');

module.exports = {
  preprocess: sveltePreprocess({
    typescript: {
      transpileOnly: true,
      compilerOptions: {
        noEmit: false,
      },
    },
    postcss: {
      'postcss-preset-env': true,
      'postcss-import': true,
    },
  }),
};

```

**Comment by PepsRyuu** [comment]
Not able to reproduce it, so relying on a test case that omits ```sourcesContent``` for regression purposes. I suspect it's the TypeScript or PostCSS plugin that's outputting a file that compiles to nothing or something like that but that's just speculation.

I've released this PR in ```0.13.13```. Let me know if it resolves the issue! :)

**Comment by pillowsoft** [comment]
That resolved the issue! Thanks so much!

**Pull request merged**
