### PR TITLE
Fix circular hoisting for variable patterns

### PR DESCRIPTION
**Pull request by PepsRyuu**

### CODE REVIEW

**Comment by charlag** [comment]
I tried it out and got this error:
```
nollup-int:///../libs/cborg.js:122
    ( useBuffer = globalThis.process && !globalThis.process.browser && globalThis.Buffer && typeof globalThis.Buffer.isBuffer === 'function');
    ^

TypeError: Class constructor Token cannot be invoked without 'new'
    at eval (nollup-int:///../libs/cborg.js:122:5)

```

I don't see where exactly it is yet

**Comment by charlag** [comment]
I think the problem is that you should put semicolon *before* the parens, otherwise javascript happens:

```
Token = class Token {

  constructor(type, value, encodedLength) {

    this.type = type;

    this.value = value;

    this.encodedLength = encodedLength;

    this.encodedBytes = undefined;

  }

  toString() {

    return `Token[${ this.type }].${ this.value }`;

  }

}



    ( useBuffer = globalThis.process && !globalThis.process.browser && globalThis.Buffer && typeof globalThis.Buffer.isBuffer === 'function');

```

it tries to call the previous class here

I would generate like `;(useBuffer = ... )`

**Comment by PepsRyuu** [comment]
Great catch, let me try reproduce it and see what I can do!

**Comment by charlag** [comment]
Hey
I think importing testdouble still does not work for us:
```
nollup-int:///../node_modules/testdouble/lib/index.js:50
    function: function_1.default,
                         ^

TypeError: Cannot read property 'default' of undefined
    at eval (nollup-int:///../node_modules/testdouble/lib/index.js:50:26)
    at file:///home/ivk/dev/repositories/tutanota-3/test/build/Suite.js:88215:21
```

(which is from lodash I think)

**Comment by PepsRyuu** [comment]
Do you have an exact replica of that issue? Using the original code presented, I'm getting a different error entirely (which seems to be a compatible issue with @rollup/plugin-commonjs overriding ```module``` unexpectedly).

**Comment by charlag** [comment]
How I would love for people to start actually writing ESM code...

I can tell you how to reproduce it with our project but it will be hard to debug probably.

Do you have any suggestion how to make testdouble work for us?

**Comment by PepsRyuu** [comment]
I have a bit of free time to look into this, seems like it could potentially be a growing problem. Can you confirm that it is working with Rollup? There also seems to be a ```dist``` version of ```testdouble```, have you tried using ```@rollup/plugin-alias``` and pointing it to that file directly?

**Comment by PepsRyuu** [comment]
Looks like I was mistaken thinking it works with Rollup, it doesn't as far as I can tell. Fails to find the import due to the ```.default.default``` issue. 

image

**Comment by PepsRyuu** [comment]
image

Looks like there's a flag on the CJS for this exact problem and it works.

**Comment by charlag** [comment]
@PepsRyuu it might break some other cases but I will try that soon, thanks!

**Comment by PepsRyuu** [comment]
Pushed an update, fixing other issues that caused this to break, namely the module shadowing, and synthetic exports not checking if the property was already exported.

**Comment by charlag** [comment]
Somehow [3f1c0b1](https://github.com/PepsRyuu/nollup/pull/227/commits/3f1c0b143b78cd5fb18a6d74f62b6a31271d08c9) and `defaultIsModuleExports: true` (w/ plugin-commonjs 18.1.0) didn't help, same error.

I will probably come back to it when I am back from holiday.

**Pull request merged**
