### PR TITLE
added hmr statuses, statuses events and logging them if "verbose" is passed to the dev-middleware

### PR DESCRIPTION
**Pull request by vzaidman**
mimicked the statuses from webpack:
https://webpack.js.org/api/hot-module-replacement/#status

### CODE REVIEW

**Comment by vzaidman** [comment]
not sure how to test it (besides the test i did with my library when this library is npm linked)

**Comment by PepsRyuu** [comment]
Looks interesting! I'll give it a thorough look through as soon as I can. 🙂

**Comment by vzaidman** [comment]
this is how i intend to use it:
https://github.com/welldone-software/why-did-you-render/commit/39c2e49515640225646273a6738c2e1f1c9b2e43#diff4

(notice the addStatusHandler)

**Comment by PepsRyuu** [comment]
Had a review over it. Seems to work well! I wouldn't worry about test cases for the time-being. I really should get around to adding them for the dev server, but I'll figure that out another day.

Was there any other changes you were planning to make? If not I'll go ahead to merge and release.

**Comment by vzaidman** [comment]
nope. thats all for now

**Comment by PepsRyuu** [comment]
Released in 0.2.4! Thanks for the excellent contribution! 😉👍

**Pull request merged**
